#!/usr/bin/env python3
"""Web UI for browsing chess puzzles generated by puzzles.py."""

import os
import chess
import chess.pgn
import chess.engine
from flask import Flask, render_template, jsonify, request
from stats import generate_stats_for_file, analyze_puzzle_tactics, build_player_stats, STATS_DIR
import db

app = Flask(__name__)

PUZZLE_DIR = os.path.dirname(os.path.abspath(__file__))


def load_puzzles(pgn_path):
    puzzles = []
    with open(pgn_path) as f:
        while True:
            game = chess.pgn.read_game(f)
            if game is None:
                break
            h = game.headers
            # Get the solution move and comment
            mainline = list(game.mainline())
            solution_san = mainline[0].move if mainline else None
            comment = mainline[0].comment if mainline else ""
            board = chess.Board(h.get("FEN", chess.STARTING_FEN))
            puzzles.append({
                "fen": h.get("FEN", chess.STARTING_FEN),
                "solution_uci": solution_san.uci() if solution_san else "",
                "solution_san": board.san(solution_san) if solution_san else "",
                "comment": comment,
                "white": h.get("White", "?"),
                "black": h.get("Black", "?"),
                "event": h.get("Event", "?"),
                "date": h.get("Date", "?"),
                "reason": h.get("PuzzleReason", ""),
                "move_number": h.get("PuzzleMove", ""),
                "turn": h.get("PuzzleTurn", "white"),
                "acceptable_uci": [x for x in h.get("PuzzleAcceptable", "").split(",") if x],
                "tactics": [x for x in h.get("PuzzleTactics", "").split(",") if x],
            })
    return puzzles


def list_pgn_files():
    return sorted(f for f in os.listdir(PUZZLE_DIR) if f.endswith(".pgn"))


@app.route("/")
def index():
    return render_template("index.html", pgn_files=list_pgn_files())


@app.route("/player/<username>")
def player_page(username):
    user = db.get_user(username)
    if not user:
        return "User not found", 404
    return render_template("player.html", username=username)


@app.route("/api/puzzles")
def api_puzzles():
    pgn_file = request.args.get("file", "")
    if not pgn_file or "/" in pgn_file or "\\" in pgn_file:
        return jsonify([])
    path = os.path.join(PUZZLE_DIR, pgn_file)
    if not os.path.isfile(path):
        return jsonify([])
    return jsonify(load_puzzles(path))


@app.route("/api/generate", methods=["POST"])
def api_generate():
    import subprocess
    data = request.get_json()
    pgn_file = data.get("file", "")
    player = data.get("player", "")
    if not pgn_file or "/" in pgn_file or "\\" in pgn_file:
        return jsonify({"error": "Invalid file"}), 400
    path = os.path.join(PUZZLE_DIR, pgn_file)
    if not os.path.isfile(path):
        return jsonify({"error": "File not found"}), 404
    out_name = pgn_file.rsplit(".", 1)[0] + "_puzzles.pgn"
    out_path = os.path.join(PUZZLE_DIR, out_name)
    cmd = ["python", "-u", os.path.join(PUZZLE_DIR, "puzzles.py"), path, "-o", out_path]
    if player:
        cmd += ["-p", player]

    def stream():
        proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1)
        for line in proc.stdout:
            yield f"data: {line.rstrip()}\n\n"
        proc.wait()
        yield f"data: [DONE:{out_name}]\n\n"

    return app.response_class(stream(), mimetype="text/event-stream")


@app.route("/api/stats/generate", methods=["POST"])
def api_stats_generate():
    """Generate stats for a puzzle PGN file. Classifies tactics and saves per-player."""
    data = request.get_json()
    pgn_file = data.get("file", "")
    player = data.get("player", "")
    if not pgn_file or "/" in pgn_file or "\\" in pgn_file:
        return jsonify({"error": "Invalid file"}), 400
    path = os.path.join(PUZZLE_DIR, pgn_file)
    if not os.path.isfile(path):
        return jsonify({"error": "File not found"}), 404
    results = generate_stats_for_file(path, player_name=player or None)
    return jsonify([{"player": name, "stats": stats, "path": p} for name, stats, p in results])


@app.route("/api/stats/players")
def api_stats_players():
    """List all players with saved stats."""
    if not os.path.isdir(STATS_DIR):
        return jsonify([])
    import json
    players = []
    for f in sorted(os.listdir(STATS_DIR)):
        if f.endswith(".json"):
            with open(os.path.join(STATS_DIR, f)) as fh:
                data = json.load(fh)
                players.append({
                    "file": f,
                    "player": data.get("player", f),
                    "aggregate": data.get("aggregate", {}),
                })
    return jsonify(players)


@app.route("/api/stats/player/<name>")
def api_stats_player(name):
    """Get full stats for a player."""
    import json
    safe = name.replace(" ", "_").lower()
    path = os.path.join(STATS_DIR, f"{safe}.json")
    if not os.path.isfile(path):
        return jsonify({"error": "Player not found"}), 404
    with open(path) as f:
        return jsonify(json.load(f))


@app.route("/api/stats/live")
def api_stats_live():
    """Compute stats on-the-fly from a puzzle PGN without saving."""
    pgn_file = request.args.get("file", "")
    player = request.args.get("player", "")
    if not pgn_file or "/" in pgn_file or "\\" in pgn_file:
        return jsonify({"error": "Invalid file"}), 400
    path = os.path.join(PUZZLE_DIR, pgn_file)
    if not os.path.isfile(path):
        return jsonify({"error": "File not found"}), 404
    puzzles = analyze_puzzle_tactics(path)
    if player:
        stats = build_player_stats(puzzles, player)
        return jsonify(stats or {"error": "Player not found in puzzles"})
    # Return stats for all players
    names = set()
    for p in puzzles:
        if p["white"] != "?": names.add(p["white"])
        if p["black"] != "?": names.add(p["black"])
    all_stats = {}
    for name in sorted(names):
        s = build_player_stats(puzzles, name)
        if s:
            all_stats[name] = s
    return jsonify(all_stats)


PROFILE_PATH = os.path.join(PUZZLE_DIR, "active_profile.json")


def get_active_profile():
    import json
    if os.path.isfile(PROFILE_PATH):
        with open(PROFILE_PATH) as f:
            return json.load(f)
    return None


@app.route("/api/profile", methods=["GET"])
def api_profile_get():
    import json
    p = get_active_profile()
    if not p:
        return jsonify({"active": False})
    # Attach saved stats if they exist
    safe = p["name"].replace(" ", "_").lower()
    stats_path = os.path.join(STATS_DIR, f"{safe}.json")
    stats = None
    if os.path.isfile(stats_path):
        with open(stats_path) as f:
            stats = json.load(f)
    return jsonify({"active": True, "name": p["name"], "stats": stats})


@app.route("/api/profile", methods=["POST"])
def api_profile_set():
    import json
    data = request.get_json()
    name = data.get("name", "").strip()
    if not name:
        return jsonify({"error": "Name required"}), 400
    with open(PROFILE_PATH, "w") as f:
        json.dump({"name": name}, f)
    return jsonify({"ok": True, "name": name})


@app.route("/api/profile", methods=["DELETE"])
def api_profile_clear():
    if os.path.isfile(PROFILE_PATH):
        os.remove(PROFILE_PATH)
    return jsonify({"ok": True})


@app.route("/api/import-games", methods=["POST"])
def api_import_games():
    """Fetch new games from Chess.com and append to master PGN."""
    from import_games import fetch_new_games, MASTER_PGN
    count = fetch_new_games()
    return jsonify({"imported": count, "file": os.path.basename(MASTER_PGN)})


@app.route("/api/import-games", methods=["DELETE"])
def api_clear_games():
    """Clear imported games and reset import state."""
    from import_games import MASTER_PGN, STATE_FILE
    for f in (MASTER_PGN, STATE_FILE):
        if os.path.isfile(f):
            os.remove(f)
    return jsonify({"ok": True})


@app.route("/api/trends")
def api_trends():
    """Compute blunder rate per game over time.
    
    - 'games' (optional): original game PGN — used for Stockfish analysis if no puzzles provided
    - 'puzzles' (optional): pre-generated puzzle PGN — fast path, no engine needed
    - At least one must be provided. If puzzle file has GameMoves headers, games file is unnecessary.
    """
    games_file = request.args.get("games", "")
    puzzles_file = request.args.get("puzzles", "")
    player = request.args.get("player", "")

    for f in (games_file, puzzles_file):
        if f and ("/" in f or "\\" in f):
            return jsonify({"error": "Invalid file"}), 400

    puzzles_path = os.path.join(PUZZLE_DIR, puzzles_file) if puzzles_file else None
    games_path = os.path.join(PUZZLE_DIR, games_file) if games_file else None

    if not (games_path and os.path.isfile(games_path or "")) and not (puzzles_path and os.path.isfile(puzzles_path or "")):
        return jsonify({"error": "Provide at least one valid file"}), 400

    # Fast path: use puzzle PGN
    if puzzles_path and os.path.isfile(puzzles_path):
        game_blunders = {}  # key -> {blunders, game_moves, date, game}
        with open(puzzles_path) as f:
            while True:
                g = chess.pgn.read_game(f)
                if g is None:
                    break
                h = g.headers
                turn = h.get("PuzzleTurn", "")
                white, black = h.get("White", "?"), h.get("Black", "?")
                date = h.get("Date", "????.??.??")
                gm = int(h.get("GameMoves", "0"))
                if player:
                    pl = player.lower()
                    if turn == "white" and pl not in white.lower():
                        continue
                    if turn == "black" and pl not in black.lower():
                        continue
                key = f"{white}|{black}|{date}"
                if key not in game_blunders:
                    game_blunders[key] = {"blunders": 0, "game_moves": gm,
                                          "date": date, "game": f"{white} vs {black}"}
                game_blunders[key]["blunders"] += 1
                if gm > game_blunders[key]["game_moves"]:
                    game_blunders[key]["game_moves"] = gm

        # Fill missing move counts from games file if needed
        needs_moves = any(v["game_moves"] == 0 for v in game_blunders.values())
        if needs_moves and games_path and os.path.isfile(games_path):
            with open(games_path) as f:
                while True:
                    g = chess.pgn.read_game(f)
                    if g is None:
                        break
                    h = g.headers
                    key = f"{h.get('White','?')}|{h.get('Black','?')}|{h.get('Date','????.??.??')}"
                    if key in game_blunders and game_blunders[key]["game_moves"] == 0:
                        game_blunders[key]["game_moves"] = sum(1 for _ in g.mainline())

        series = []
        for v in game_blunders.values():
            rate = round(v["blunders"] / v["game_moves"], 4) if v["game_moves"] > 0 else 0
            series.append({"date": v["date"], "game": v["game"],
                          "blunders": v["blunders"], "total_moves": v["game_moves"],
                          "blunder_rate": rate})
        return jsonify(sorted(series, key=lambda x: x["date"]))

    # Slow path: run Stockfish on game PGN
    if not games_path or not os.path.isfile(games_path):
        return jsonify({"error": "Games file not found"}), 404

    from puzzles import download_stockfish, evaluate, score_to_cp
    stockfish_path = download_stockfish()
    engine = chess.engine.SimpleEngine.popen_uci(stockfish_path)
    series = []
    try:
        with open(games_path) as f:
            while True:
                g = chess.pgn.read_game(f)
                if g is None:
                    break
                h = g.headers
                white, black = h.get("White", "?"), h.get("Black", "?")
                if player:
                    pl = player.lower()
                    if pl not in white.lower() and pl not in black.lower():
                        continue
                board = g.board()
                prev_score = evaluate(engine, board, 15)
                blunders = 0
                total_moves = 0
                for node in g.mainline():
                    turn = board.turn
                    board.push(node.move)
                    curr_score = evaluate(engine, board, 15)
                    total_moves += 1
                    drop = (score_to_cp(prev_score) - score_to_cp(curr_score)) if turn == chess.WHITE else (score_to_cp(curr_score) - score_to_cp(prev_score))
                    if drop >= 200:
                        if not player or (player.lower() in (white if turn == chess.WHITE else black).lower()):
                            blunders += 1
                    prev_score = curr_score
                rate = round(blunders / total_moves, 4) if total_moves > 0 else 0
                series.append({"date": h.get("Date", "????.??.??"),
                              "game": f"{white} vs {black}",
                              "blunders": blunders, "total_moves": total_moves,
                              "blunder_rate": rate})
    finally:
        engine.quit()
    return jsonify(series)


# --- Database API endpoints ---

@app.route("/api/db/users", methods=["GET"])
def api_db_users():
    users = [dict(u) for u in db.list_users()]
    return jsonify(users)


@app.route("/api/db/users", methods=["POST"])
def api_db_create_user():
    data = request.get_json()
    username = data.get("username", "").strip()
    chess_com = data.get("chess_com_username", "").strip() or None
    if not username:
        return jsonify({"error": "Username required"}), 400
    try:
        user = db.create_user(username, chess_com)
        return jsonify(dict(user))
    except Exception as e:
        return jsonify({"error": str(e)}), 409


@app.route("/api/db/users/<username>", methods=["GET"])
def api_db_get_user(username):
    user = db.get_user(username)
    if not user:
        return jsonify({"error": "User not found"}), 404
    return jsonify(dict(user))


@app.route("/api/db/users/<username>", methods=["DELETE"])
def api_db_delete_user(username):
    if db.delete_user(username):
        return jsonify({"ok": True})
    return jsonify({"error": "User not found"}), 404


@app.route("/api/db/users/<username>/games", methods=["GET"])
def api_db_user_games(username):
    user = db.get_user(username)
    if not user:
        return jsonify({"error": "User not found"}), 404
    limit = request.args.get("limit", type=int)
    games = [dict(g) for g in db.get_user_games(user["id"], limit)]
    return jsonify(games)


@app.route("/api/db/users/<username>/games/<int:game_id>", methods=["DELETE"])
def api_db_delete_game(username, game_id):
    db.delete_game(game_id)
    return jsonify({"ok": True})


@app.route("/api/db/users/<username>/import", methods=["POST"])
def api_db_import_games(username):
    """Import games from Chess.com into the database for a user."""
    import requests as req
    user = db.get_user(username)
    if not user:
        return jsonify({"error": "User not found"}), 404
    chess_com_user = (request.json or {}).get("chess_com_username") or user["chess_com_username"] or username
    from_date = (request.json or {}).get("from_date", "")
    to_date = (request.json or {}).get("to_date", "")
    headers = {"User-Agent": "FischerChess/1.0"}

    r = req.get(f"https://api.chess.com/pub/player/{chess_com_user}/games/archives", headers=headers)
    if r.status_code != 200:
        return jsonify({"error": f"Chess.com API error: {r.status_code}"}), 400
    archives = r.json().get("archives", [])

    imported = 0
    for url in archives:
        r = req.get(url, headers=headers)
        if r.status_code != 200:
            continue
        for game in r.json().get("games", []):
            pgn_text = game.get("pgn", "")
            if not pgn_text:
                continue
            chess_com_id = game.get("url", "")
            import io
            g = chess.pgn.read_game(io.StringIO(pgn_text))
            if not g:
                continue
            h = g.headers
            game_date = h.get("Date", "").replace(".", "-")
            if from_date and game_date < from_date:
                continue
            if to_date and game_date > to_date:
                continue
            total_moves = sum(1 for _ in g.mainline())
            game_id = db.save_game(
                user["id"], pgn_text, h.get("White", "?"), h.get("Black", "?"),
                h.get("Result", "*"), h.get("Date", ""), h.get("Event", ""),
                total_moves, chess_com_id
            )
            if game_id:
                imported += 1

    return jsonify({"imported": imported, "username": username})


@app.route("/api/db/users/<username>/import-pgn", methods=["POST"])
def api_db_import_pgn(username):
    """Import games from an uploaded PGN file."""
    user = db.get_user(username)
    if not user:
        return jsonify({"error": "User not found"}), 404
    file = request.files.get("file")
    if not file:
        return jsonify({"error": "No file uploaded"}), 400
    import io
    pgn_text_all = file.read().decode("utf-8", errors="ignore")
    stream = io.StringIO(pgn_text_all)
    imported = 0
    while True:
        g = chess.pgn.read_game(stream)
        if g is None:
            break
        h = g.headers
        total_moves = sum(1 for _ in g.mainline())
        pgn_str = str(g)
        game_id = db.save_game(
            user["id"], pgn_str, h.get("White", "?"), h.get("Black", "?"),
            h.get("Result", "*"), h.get("Date", ""), h.get("Event", ""),
            total_moves, None
        )
        if game_id:
            imported += 1
    return jsonify({"imported": imported, "username": username})


@app.route("/api/db/users/<username>/puzzles", methods=["GET"])
def api_db_user_puzzles(username):
    user = db.get_user(username)
    if not user:
        return jsonify({"error": "User not found"}), 404
    limit = request.args.get("limit", type=int)
    puzzles = [dict(p) for p in db.get_user_puzzles(user["id"], limit)]
    return jsonify(puzzles)


@app.route("/api/db/users/<username>/puzzle-queue", methods=["GET"])
def api_db_puzzle_queue(username):
    user = db.get_user(username)
    if not user:
        return jsonify({"error": "User not found"}), 404
    puzzles = [dict(p) for p in db.get_queue_puzzles(user["id"])]
    return jsonify(puzzles)


@app.route("/api/db/puzzles/<int:puzzle_id>/status", methods=["PUT"])
def api_db_update_puzzle_status(puzzle_id):
    data = request.get_json() or {}
    status = data.get("status")
    if status not in ("active", "solved_first_try", "solved_retry", "archived", "bookmarked"):
        return jsonify({"error": "Invalid status"}), 400
    new_badges = db.update_puzzle_status(puzzle_id, status)
    return jsonify({"ok": True, "new_badges": new_badges or []})


@app.route("/api/db/users/<username>/badges", methods=["GET"])
def api_db_user_badges(username):
    user = db.get_user(username)
    if not user:
        return jsonify({"error": "User not found"}), 404
    from badges import get_user_badges, BADGES
    conn = db.get_db()
    try:
        earned = [dict(r) for r in get_user_badges(conn, user["id"])]
        return jsonify({"earned": earned, "definitions": BADGES})
    finally:
        conn.close()


@app.route("/api/db/users/<username>/generate-puzzles", methods=["POST"])
def api_db_generate_puzzles(username):
    """Generate puzzles from user's games in DB and save them."""
    user = db.get_user(username)
    if not user:
        return jsonify({"error": "User not found"}), 404

    from puzzles import download_stockfish, analyze_game, evaluate
    from tactics import classify_tactic
    import chess.engine as ce

    data = request.get_json() or {}
    threshold = data.get("threshold", 200)
    depth = data.get("depth", 15)
    limit = data.get("limit", 50)  # max games to analyze
    player_name = data.get("player_name", "").strip()  # name as it appears in PGN headers

    games = db.get_user_games(user["id"], limit)
    if not games:
        return jsonify({"error": "No games found"}), 404

    stockfish_path = download_stockfish()
    engine = ce.SimpleEngine.popen_uci(stockfish_path)
    engine.configure({"Hash": 64, "Threads": 1})
    total_puzzles = 0

    try:
        for game_row in games:
            import io
            g = chess.pgn.read_game(io.StringIO(game_row["pgn"]))
            if not g:
                continue
            puzzles = analyze_game(engine, g, threshold, depth)
            # Filter to user's blunders only if player_name specified
            filter_name = player_name.lower() if player_name else (user["chess_com_username"] or "").lower()
            for p in puzzles:
                if filter_name:
                    is_user = (p["turn"] == "white" and filter_name in game_row["white"].lower()) or \
                              (p["turn"] == "black" and filter_name in game_row["black"].lower())
                    if not is_user:
                        continue
                db.save_puzzle(
                    user["id"], game_row["id"], p["fen"],
                    p["best_move_uci"], p["best_move"], p["played"],
                    p["reason"], p["drop"], p["move_number"], p["turn"],
                    ",".join(p.get("tactics", [])),
                    ",".join(p.get("acceptable_uci", []))
                )
                total_puzzles += 1
    finally:
        engine.quit()

    return jsonify({"puzzles_generated": total_puzzles, "games_analyzed": len(games)})


@app.route("/api/db/users/<username>/stats", methods=["GET"])
def api_db_user_stats(username):
    user = db.get_user(username)
    if not user:
        return jsonify({"error": "User not found"}), 404
    return jsonify(db.get_user_stats(user["id"]))


@app.route("/api/db/users/<username>/trends", methods=["GET"])
def api_db_user_trends(username):
    user = db.get_user(username)
    if not user:
        return jsonify({"error": "User not found"}), 404
    return jsonify(db.get_user_trends(user["id"]))


if __name__ == "__main__":
    app.run(debug=True, host='0.0.0.0', port=5001)
